"""ProjectFacts 本轮支持的参数定义。"""

from __future__ import annotations

from typing import Any


PARAMETER_DEFINITIONS: list[dict[str, Any]] = [
    {
        "parameter": "support_system",
        "name": "支撑体系",
        "canonical_unit": None,
        "aliases": [
            "承插型盘扣式钢管支架",
            "承插型盘扣式支撑架",
            "盘扣式支撑架",
            "盘扣式模板支架",
            "盘扣架",
            "盘扣式钢管架",
            "支架形式",
        ],
        "preferred_sections": ["工程概况", "施工工艺技术", "模板支撑体系", "技术参数", "编制依据"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "categorical_semantic",
    },
    {
        "parameter": "support_height",
        "name": "支撑架搭设高度",
        "canonical_unit": "m",
        "aliases": ["支撑架搭设高度", "支模架搭设高度", "模板支架高度", "支架高度", "支撑高度", "搭设高度", "支模高度"],
        "preferred_sections": ["工程概况", "施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "exclude_terms": ["丝杆外露", "螺杆外露", "插入"],
    },
    {
        "parameter": "standard_step_height",
        "name": "架体标准步距",
        "canonical_unit": "m",
        "aliases": ["步距", "水平杆步距", "标准步距", "架体步距", "水平拉杆步距", "中间层水平杆最大竖向步距"],
        "preferred_sections": ["施工工艺技术", "模板支撑体系", "支撑架", "技术参数", "支架设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0.1,
        "plausible_max": 5.0,
        "exclude_terms": ["悬臂", "伸出顶层水平杆", "插入", "顶层步距", "顶部水平杆步距", "顶层水平杆步距"],
    },
    {
        "parameter": "head_jack_cantilever_length",
        "name": "可调托撑悬臂长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑悬臂长度", "顶托悬臂长度", "伸出顶层水平杆", "顶托伸出长度", "托座伸出顶层水平杆", "支撑点至顶层水平杆中心线"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0,
        "plausible_max": 2000,
    },
    {
        "parameter": "horizontal_scissor_brace_interval",
        "name": "水平剪刀撑沿高度设置间隔",
        "canonical_unit": None,
        "aliases": ["水平剪刀撑", "每间隔", "标准步距", "步距设置水平剪刀撑"],
        "preferred_sections": ["模板体系设计", "架体构造措施", "施工工艺技术", "施工要点", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body", "parameter_table", "calculation"],
        "extraction_mode": "standard_step_interval",
    },
    {
        "parameter": "head_jack_screw_exposed_length",
        "name": "可调托撑丝杆外露长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑丝杆外露", "顶托丝杆外露", "丝杆外露长度", "螺杆外露长度", "螺杆伸出长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
    },
    {
        "parameter": "head_jack_insertion_length",
        "name": "可调托撑插入长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑插入", "顶托插入", "托撑插入", "插入立杆长度", "托撑插入深度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["托撑", "顶托", "托座"],
        "exclude_terms": ["底座", "可调底座", "悬臂", "外露"],
    },
    {
        "parameter": "base_jack_insertion_length",
        "name": "可调底座丝杆插入立杆长度",
        "canonical_unit": "mm",
        "aliases": ["可调底座插入", "底座插入长度", "底座丝杆插入", "底座插入立杆长度", "可调底座丝杆插入立杆长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["底座", "可调底座"],
    },
    {
        "parameter": "sweeper_centerline_height_above_base_plate",
        "name": "扫地杆中心线距可调底座底板高度",
        "canonical_unit": "mm",
        "aliases": ["扫地杆高度", "最底层水平杆高度", "扫地杆中心线", "距底座上皮", "距底板高度", "离地高度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "构造要求", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["扫地杆", "底座", "底板", "最底层水平杆"],
    },
    {
        "parameter": "personnel_equipment_load_standard",
        "name": "施工人员及设备荷载标准值",
        "canonical_unit": "kN/m2",
        "aliases": ["施工人员及设备荷载", "人员及设备荷载", "人员设备荷载", "施工人员荷载"],
        "preferred_sections": ["荷载设计", "施工工艺技术", "技术参数", "计算书", "荷载参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "numeric",
        "include_terms": ["施工人员", "设备荷载"],
        "exclude_terms": ["振捣", "泵送", "倾倒", "风荷载", "组合", "设计值"],
    },
    {
        "parameter": "permanent_load_items",
        "name": "永久荷载项目集合",
        "canonical_unit": None,
        "aliases": ["永久荷载", "荷载标准值", "荷载名称", "架体自重", "模板自重", "新浇混凝土自重", "钢筋自重", "G1", "G2", "G3"],
        "preferred_sections": ["荷载设计", "荷载计算", "设计荷载", "荷载标准值", "计算参数", "计算书", "模板计算", "支撑架计算", "设计参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "load_item_set",
        "aggregation_mode": "set_union",
        "load_items": [
            {
                "id": "formwork_support_self_weight",
                "aliases": ["模板及支架自重", "模板及支撑架自重", "模板及小楞", "模板自重", "支架自重", "架体自重", "G1", "G2"],
                "include_context": ["自重", "G1", "G2", "模板", "支架", "架体"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "fresh_concrete_self_weight",
                "aliases": ["新浇混凝土自重", "混凝土自重", "新浇砼自重", "混凝土容重", "G3"],
                "include_context": ["混凝土", "砼", "G3"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "reinforcement_self_weight",
                "aliases": ["钢筋自重", "钢筋荷载", "钢筋混凝土自重", "G3"],
                "include_context": ["钢筋", "G3"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
        ],
    },
    {
        "parameter": "variable_load_items",
        "name": "可变荷载项目集合",
        "canonical_unit": None,
        "aliases": ["可变荷载", "施工荷载", "施工人员及设备荷载", "振捣混凝土荷载", "泵送混凝土", "附加水平荷载", "风荷载", "Q1", "Q2", "Q3"],
        "preferred_sections": ["荷载设计", "荷载计算", "设计荷载", "荷载标准值", "计算参数", "计算书", "模板计算", "支撑架计算", "设计参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "load_item_set",
        "aggregation_mode": "set_union",
        "load_items": [
            {
                "id": "personnel_equipment_load",
                "aliases": ["施工人员及设备荷载", "人员及设备荷载", "施工人员荷载", "施工荷载"],
                "include_context": ["施工人员", "设备", "施工荷载"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "concrete_vibration_load",
                "aliases": ["振捣混凝土荷载", "振捣荷载", "混凝土振捣"],
                "include_context": ["振捣"],
                "exclude_context": ["不得", "不应"],
            },
            {
                "id": "concrete_pumping_load",
                "aliases": ["泵送混凝土", "泵送荷载", "倾倒混凝土荷载", "倾倒荷载", "附加水平荷载", "Q2"],
                "include_context": ["泵送", "倾倒", "附加水平", "Q2"],
                "exclude_context": ["不得", "不应"],
            },
            {
                "id": "wind_load",
                "aliases": ["风荷载", "Q3"],
                "include_context": ["风荷载", "Q3"],
                "exclude_context": ["不考虑", "未考虑", "不得", "不应"],
            },
        ],
    },
]


def get_parameter_definitions() -> list[dict[str, Any]]:
    return [dict(item) for item in PARAMETER_DEFINITIONS]
