"""ProjectFacts 本轮支持的参数定义。"""

from __future__ import annotations

from typing import Any


PARAMETER_DEFINITIONS: list[dict[str, Any]] = [
    {
        "parameter": "support_system",
        "name": "支撑体系",
        "canonical_unit": None,
        "aliases": [
            "承插型盘扣式钢管支架",
            "承插型盘扣式支撑架",
            "盘扣式支撑架",
            "盘扣式模板支架",
            "盘扣架",
            "盘扣式钢管架",
            "支架形式",
        ],
        "preferred_sections": ["工程概况", "施工工艺技术", "模板支撑体系", "技术参数", "编制依据"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "categorical_semantic",
    },
    {
        "parameter": "support_height",
        "name": "支撑架搭设高度",
        "canonical_unit": "m",
        "aliases": ["支撑架搭设高度", "支模架搭设高度", "模板支架高度", "支架高度", "支撑高度", "搭设高度", "支模高度"],
        "preferred_sections": ["工程概况", "施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        # 多区域多值时取最大值：≥8m 超规模判定只关心最大搭设高度，
        # 全部候选证据保留供人工复核
        "resolution_mode": "max_numeric",
        "plausible_min": 1.0,
        "plausible_max": 50.0,
        "exclude_terms": ["丝杆外露", "螺杆外露", "插入"],
    },
    {
        "parameter": "standard_step_height",
        "name": "架体标准步距",
        "canonical_unit": "m",
        "aliases": ["步距", "水平杆步距", "标准步距", "架体步距", "水平拉杆步距", "中间层水平杆最大竖向步距"],
        "preferred_sections": ["施工工艺技术", "模板支撑体系", "支撑架", "技术参数", "支架设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0.1,
        "plausible_max": 5.0,
        "exclude_terms": ["悬臂", "伸出顶层水平杆", "插入", "顶层步距", "顶部水平杆步距", "顶层水平杆步距"],
    },
    {
        "parameter": "head_jack_cantilever_length",
        "name": "可调托撑悬臂长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑悬臂长度", "顶托悬臂长度", "伸出顶层水平杆", "顶托伸出长度", "托座伸出顶层水平杆", "支撑点至顶层水平杆中心线"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0,
        "plausible_max": 2000,
    },
    {
        "parameter": "horizontal_scissor_brace_interval",
        "name": "水平剪刀撑沿高度设置间隔",
        "canonical_unit": None,
        "aliases": ["水平剪刀撑", "每间隔", "标准步距", "步距设置水平剪刀撑"],
        "preferred_sections": ["模板体系设计", "架体构造措施", "施工工艺技术", "施工要点", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body", "parameter_table", "calculation"],
        "extraction_mode": "standard_step_interval",
    },
    {
        "parameter": "head_jack_screw_exposed_length",
        "name": "可调托撑丝杆外露长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑丝杆外露", "顶托丝杆外露", "丝杆外露长度", "螺杆外露长度", "螺杆伸出长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
    },
    {
        "parameter": "head_jack_insertion_length",
        "name": "可调托撑插入长度",
        "canonical_unit": "mm",
        "aliases": ["可调托撑插入", "顶托插入", "托撑插入", "插入立杆长度", "托撑插入深度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["托撑", "顶托", "托座"],
        "exclude_terms": ["底座", "可调底座", "悬臂", "外露"],
    },
    {
        "parameter": "base_jack_insertion_length",
        "name": "可调底座丝杆插入立杆长度",
        "canonical_unit": "mm",
        "aliases": ["可调底座插入", "底座插入长度", "底座丝杆插入", "底座插入立杆长度", "可调底座丝杆插入立杆长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["底座", "可调底座"],
    },
    {
        "parameter": "sweeper_centerline_height_above_base_plate",
        "name": "扫地杆中心线距可调底座底板高度",
        "canonical_unit": "mm",
        "aliases": ["扫地杆高度", "最底层水平杆高度", "扫地杆中心线", "距底座上皮", "距底板高度", "离地高度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "构造要求", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["扫地杆", "底座", "底板", "最底层水平杆"],
    },
    {
        "parameter": "personnel_equipment_load_standard",
        "name": "施工人员及设备荷载标准值",
        "canonical_unit": "kN/m2",
        "aliases": ["施工人员及设备荷载", "人员及设备荷载", "人员设备荷载", "施工人员荷载"],
        "preferred_sections": ["荷载设计", "施工工艺技术", "技术参数", "计算书", "荷载参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "numeric",
        "include_terms": ["施工人员", "设备荷载"],
        "exclude_terms": ["振捣", "泵送", "倾倒", "风荷载", "组合", "设计值"],
    },
    {
        "parameter": "permanent_load_items",
        "name": "永久荷载项目集合",
        "canonical_unit": None,
        "aliases": ["永久荷载", "荷载标准值", "荷载名称", "架体自重", "模板自重", "新浇混凝土自重", "钢筋自重", "G1", "G2", "G3"],
        "preferred_sections": ["荷载设计", "荷载计算", "设计荷载", "荷载标准值", "计算参数", "计算书", "模板计算", "支撑架计算", "设计参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "load_item_set",
        "aggregation_mode": "set_union",
        "load_items": [
            {
                "id": "formwork_support_self_weight",
                "aliases": ["模板及支架自重", "模板及支撑架自重", "模板及小楞", "模板自重", "支架自重", "架体自重", "G1", "G2"],
                "include_context": ["自重", "G1", "G2", "模板", "支架", "架体"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "fresh_concrete_self_weight",
                "aliases": ["新浇混凝土自重", "混凝土自重", "新浇砼自重", "混凝土容重", "G3"],
                "include_context": ["混凝土", "砼", "G3"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "reinforcement_self_weight",
                "aliases": ["钢筋自重", "钢筋荷载", "钢筋混凝土自重", "G3"],
                "include_context": ["钢筋", "G3"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
        ],
    },
    {
        "parameter": "variable_load_items",
        "name": "可变荷载项目集合",
        "canonical_unit": None,
        "aliases": ["可变荷载", "施工荷载", "施工人员及设备荷载", "振捣混凝土荷载", "泵送混凝土", "附加水平荷载", "风荷载", "Q1", "Q2", "Q3"],
        "preferred_sections": ["荷载设计", "荷载计算", "设计荷载", "荷载标准值", "计算参数", "计算书", "模板计算", "支撑架计算", "设计参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "calculation", "body"],
        "extraction_mode": "load_item_set",
        "aggregation_mode": "set_union",
        "load_items": [
            {
                "id": "personnel_equipment_load",
                "aliases": ["施工人员及设备荷载", "人员及设备荷载", "施工人员荷载", "施工荷载"],
                "include_context": ["施工人员", "设备", "施工荷载"],
                "exclude_context": ["不得", "不应", "应包括"],
            },
            {
                "id": "concrete_vibration_load",
                "aliases": ["振捣混凝土荷载", "振捣荷载", "混凝土振捣"],
                "include_context": ["振捣"],
                "exclude_context": ["不得", "不应"],
            },
            {
                "id": "concrete_pumping_load",
                "aliases": ["泵送混凝土", "泵送荷载", "倾倒混凝土荷载", "倾倒荷载", "附加水平荷载", "Q2"],
                "include_context": ["泵送", "倾倒", "附加水平", "Q2"],
                "exclude_context": ["不得", "不应"],
            },
            {
                "id": "wind_load",
                "aliases": ["风荷载", "Q3"],
                "include_context": ["风荷载", "Q3"],
                "exclude_context": ["不考虑", "未考虑", "不得", "不应"],
            },
        ],
    },
    # ===== v4.0 确定性规则扩展参数 =====
    {
        "parameter": "support_span",
        "name": "搭设跨度",
        "canonical_unit": "m",
        "aliases": ["搭设跨度", "支撑跨度", "模板跨度", "最大跨度", "跨径", "跨度", "梁跨", "板跨", "计算跨度", "最大梁跨"],
        "preferred_sections": ["工程概况", "施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 1.0,
        "plausible_max": 100.0,
    },
    {
        "parameter": "total_load",
        "name": "施工总荷载",
        "canonical_unit": "kN/m2",
        "aliases": ["施工总荷载", "总荷载", "荷载设计值", "荷载标准值合计"],
        "preferred_sections": ["荷载设计", "荷载计算", "计算书", "技术参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "numeric",
        # 不同区域/组合的总荷载天然多值，资格审查取最大值（超规模阈值判定）
        "resolution_mode": "max_numeric",
        "plausible_min": 0.1,
        "plausible_max": 200.0,
        "include_terms": ["荷载", "kN"],
    },
    {
        "parameter": "concentrated_line_load",
        "name": "集中线荷载",
        "canonical_unit": "kN/m",
        "aliases": ["集中线荷载", "线荷载", "集中线荷载设计值"],
        "preferred_sections": ["荷载设计", "荷载计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        # 不同梁的线荷载天然多值，资格审查取最大值（超规模阈值判定）
        "resolution_mode": "max_numeric",
        "plausible_min": 1.0,
        "plausible_max": 500.0,
        "include_terms": ["线荷载", "kN/m"],
    },
    {
        "parameter": "vertical_spacing",
        "name": "立杆纵距",
        "canonical_unit": "m",
        "aliases": ["立杆纵距", "纵距", "纵向间距", "立杆纵向间距"],
        "preferred_sections": ["施工工艺技术", "模板支撑体系", "技术参数", "支架设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0.2,
        "plausible_max": 3.0,
        "exclude_terms": ["横距", "步距"],
    },
    {
        "parameter": "horizontal_spacing",
        "name": "立杆横距",
        "canonical_unit": "m",
        "aliases": ["立杆横距", "横距", "横向间距", "立杆横向间距"],
        "preferred_sections": ["施工工艺技术", "模板支撑体系", "技术参数", "支架设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 0.2,
        "plausible_max": 3.0,
        "exclude_terms": ["纵距", "步距"],
    },
    {
        "parameter": "framework_height",
        "name": "架体高度",
        "canonical_unit": "m",
        "aliases": ["架体高度", "支撑架高度", "支架高度", "模板支撑高度"],
        "preferred_sections": ["工程概况", "施工工艺技术", "技术参数", "模板支撑体系"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body"],
        "extraction_mode": "numeric",
        "resolution_mode": "max_numeric",
        "plausible_min": 1.0,
        "plausible_max": 50.0,
        "exclude_terms": ["螺杆", "丝杆", "插入"],
    },
    {
        "parameter": "free_end_length",
        "name": "自由端长度",
        "canonical_unit": "mm",
        "aliases": ["自由端长度", "自由端", "顶层水平杆以上长度", "顶端自由长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "plausible_min": 0,
        "plausible_max": 1000,
    },
    {
        "parameter": "base_jack_screw_extension",
        "name": "底座螺杆外伸长度",
        "canonical_unit": "mm",
        "aliases": ["底座螺杆外伸", "底座外伸", "可调底座外伸", "底座螺杆伸出", "底座外露"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "include_terms": ["底座", "可调底座"],
        "exclude_terms": ["顶托", "托撑", "悬臂"],
    },
    {
        "parameter": "top_level_to_jack_distance",
        "name": "顶层水平杆至托撑顶面距离",
        "canonical_unit": "mm",
        "aliases": ["顶层水平杆至托撑顶面距离", "顶层水平杆到顶面", "顶层水平杆至托撑", "调节螺杆伸出长度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "模板支撑体系", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "plausible_min": 0,
        "plausible_max": 1000,
        "include_terms": ["顶层水平杆", "托撑", "螺杆伸出"],
    },
    {
        "parameter": "height_to_width_ratio",
        "name": "高宽比",
        "canonical_unit": None,
        "aliases": ["高宽比", "H/B", "高度比宽度", "架体高宽比"],
        "preferred_sections": ["施工工艺技术", "模板支撑体系", "技术参数", "计算书", "支架设计"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "numeric",
        "plausible_min": 0.1,
        "plausible_max": 20.0,
        "include_terms": ["高宽比", "H/B"],
    },
    {
        "parameter": "panel_thickness",
        "name": "面板厚度",
        "canonical_unit": "mm",
        "aliases": ["面板厚度", "模板厚度", "胶合板厚度", "覆面木胶合板厚度"],
        "preferred_sections": ["施工工艺技术", "技术参数", "材料", "模板设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "plausible_min": 5,
        "plausible_max": 50,
        "include_terms": ["面板", "模板", "胶合板"],
    },
    {
        "parameter": "steel_plate_thickness",
        "name": "钢板厚度",
        "canonical_unit": "mm",
        "aliases": ["钢板厚度", "厚度t", "插板厚度", "钢插板厚"],
        "preferred_sections": ["材料", "施工工艺技术", "技术参数", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "plausible_min": 1,
        "plausible_max": 20,
        "include_terms": ["钢板", "厚度t", "插板"],
    },
    {
        "parameter": "wall_thickness_ratio",
        "name": "实测壁厚与公称壁厚比值",
        "canonical_unit": None,
        "aliases": ["实测壁厚/公称壁厚", "壁厚比", "实测壁厚", "壁厚"],
        "preferred_sections": ["材料", "施工工艺技术", "技术参数", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["parameter_table", "body", "calculation"],
        "extraction_mode": "numeric",
        "plausible_min": 0.5,
        "plausible_max": 1.5,
        "include_terms": ["壁厚", "实测"],
    },
    {
        "parameter": "layer_thickness",
        "name": "分层厚度",
        "canonical_unit": "mm",
        "aliases": ["分层厚度", "分层浇捣厚度", "浇筑层厚度", "每层厚度"],
        "preferred_sections": ["施工工艺技术", "施工要点", "技术参数"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body", "parameter_table"],
        "extraction_mode": "numeric",
        "plausible_min": 100,
        "plausible_max": 2000,
        "include_terms": ["分层", "浇捣", "层厚"],
    },
    {
        "parameter": "pouring_speed",
        "name": "浇筑速度",
        "canonical_unit": "m/h",
        "aliases": ["浇筑速度", "浇筑速率", "浇注速度", "混凝土浇筑速度"],
        "preferred_sections": ["施工工艺技术", "荷载计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "body", "parameter_table"],
        "extraction_mode": "numeric",
        "plausible_min": 0.1,
        "plausible_max": 20.0,
        "include_terms": ["浇筑速度", "浇筑速率"],
    },
    {
        "parameter": "monitoring_point_spacing",
        "name": "监测点间距",
        "canonical_unit": "m",
        "aliases": ["监测点间距", "监测点距离", "监测点布置间距", "观测点间距"],
        "preferred_sections": ["安全保证措施", "监测监控", "施工工艺技术"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body", "parameter_table"],
        "extraction_mode": "numeric",
        "plausible_min": 1.0,
        "plausible_max": 50.0,
        "include_terms": ["监测点", "观测点", "间距"],
    },
    {
        "parameter": "wind_force_level",
        "name": "风力等级",
        "canonical_unit": "级",
        "aliases": ["风力等级", "风力", "风速等级", "大风等级"],
        "preferred_sections": ["安全保证措施", "施工工艺技术", "应急预案"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body"],
        "extraction_mode": "numeric",
        "plausible_min": 1,
        "plausible_max": 17,
        "include_terms": ["风力", "风速", "大风"],
    },
    {
        "parameter": "expert_count",
        "name": "专家数量",
        "canonical_unit": "人",
        "aliases": ["专家数量", "专家组人数", "专家成员数", "论证专家"],
        "preferred_sections": ["编制说明", "审批", "工程概况", "附件"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["body", "parameter_table"],
        "extraction_mode": "numeric",
        "plausible_min": 3,
        "plausible_max": 20,
        "include_terms": ["专家", "论证", "专家组"],
    },
    # ===== 计算输入参数（侧压力 / 面板 / 楞梁 / 地基 / 抗倾覆）=====
    {
        "parameter": "concrete_unit_weight",
        "name": "混凝土重力密度 γc",
        "canonical_unit": "kN/m3",
        "aliases": ["混凝土重力密度", "混凝土容重", "γc", "γ_c", "gamma_c", "gamma_c"],
        "preferred_sections": ["荷载设计", "荷载计算", "模板计算", "支撑架计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"γc", r"γ_c", r"gammac", r"混凝土重力密度", r"混凝土容重"],
        "plausible_min": 22.0,
        "plausible_max": 27.0,
    },
    {
        "parameter": "initial_set_time",
        "name": "混凝土初凝时间 t0",
        "canonical_unit": "h",
        "aliases": ["初凝时间", "t0", "t_0"],
        "preferred_sections": ["荷载设计", "荷载计算", "模板计算", "支撑架计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"\bt0\b", r"t_0", r"初凝时间"],
        "include_terms": ["t0", "初凝"],
        "plausible_min": 2.0,
        "plausible_max": 12.0,
    },
    {
        "parameter": "side_pressure_height",
        "name": "侧压力计算高度 H",
        "canonical_unit": "m",
        "aliases": ["侧压力计算高度", "有效压头高度", "混凝土侧压力计算位置至顶部高度", "浇筑高度"],
        "preferred_sections": ["荷载计算", "模板计算", "支撑架计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["侧压力", "H", "压头", "浇筑高度"],
        "plausible_min": 0.5,
        "plausible_max": 30.0,
    },
    {
        "parameter": "slump",
        "name": "混凝土坍落度",
        "canonical_unit": "mm",
        "aliases": ["坍落度", "坍落度(mm)", "混凝土坍落度"],
        "preferred_sections": ["荷载计算", "模板计算", "支撑架计算", "技术参数", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"坍落度", r"slump"],
        "include_terms": ["坍落度", "slump"],
        "plausible_min": 30,
        "plausible_max": 250,
    },
    {
        "parameter": "beta_correction",
        "name": "GB50666 坍落度影响修正系数 β",
        "canonical_unit": None,
        "aliases": ["β", "坍落度影响修正系数", "坍落度修正系数", "beta"],
        "preferred_sections": ["荷载计算", "模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"β(?![12])", r"beta(?![12])", r"坍落度影响修正系数"],
        "include_terms": ["β", "修正系数"],
        "plausible_min": 0.5,
        "plausible_max": 2.0,
    },
    {
        "parameter": "beta1_correction",
        "name": "JGJ162 外加剂影响修正系数 β1",
        "canonical_unit": None,
        "aliases": ["β1", "外加剂影响系数", "外加剂影响修正系数", "beta1"],
        "preferred_sections": ["荷载计算", "模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"β1", r"beta1", r"外加剂影响系数"],
        "include_terms": ["β1", "外加剂"],
        "plausible_min": 0.5,
        "plausible_max": 2.0,
    },
    {
        "parameter": "beta2_correction",
        "name": "JGJ162 坍落度影响系数 β2",
        "canonical_unit": None,
        "aliases": ["β2", "坍落度影响系数", "beta2"],
        "preferred_sections": ["荷载计算", "模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"β2", r"beta2", r"坍落度影响系数"],
        "include_terms": ["β2", "坍落度"],
        "plausible_min": 0.5,
        "plausible_max": 2.0,
    },
    {
        "parameter": "panel_section_width",
        "name": "面板计算单元宽度 b",
        "canonical_unit": "mm",
        "aliases": ["面板计算宽度", "面板单元宽度", "计算单元宽度", "面板计算单元宽度"],
        "preferred_sections": ["模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["面板", "计算宽度", "单元宽度"],
        "plausible_min": 100,
        "plausible_max": 2000,
    },
    {
        "parameter": "panel_stringer_spacing",
        "name": "次楞间距（面板跨度 l）",
        "canonical_unit": "mm",
        "aliases": ["次楞间距", "次龙骨间距", "小楞间距", "面板跨度", "面板计算跨度"],
        "preferred_sections": ["模板计算", "模板设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "numeric",
        "include_terms": ["次楞", "次龙骨", "小楞", "面板跨度"],
        "plausible_min": 100,
        "plausible_max": 600,
    },
    {
        "parameter": "stringer_section_width",
        "name": "次楞截面宽度 b",
        "canonical_unit": "mm",
        "aliases": ["次楞截面宽度", "次龙骨截面宽度", "小楞宽度", "方木宽度"],
        "preferred_sections": ["模板计算", "计算书", "材料"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["次楞", "次龙骨", "小楞", "方木"],
        "plausible_min": 30,
        "plausible_max": 200,
    },
    {
        "parameter": "stringer_section_height",
        "name": "次楞截面高度 h",
        "canonical_unit": "mm",
        "aliases": ["次楞截面高度", "次龙骨截面高度", "小楞高度", "方木高度"],
        "preferred_sections": ["模板计算", "计算书", "材料"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["次楞", "次龙骨", "小楞", "方木"],
        "plausible_min": 30,
        "plausible_max": 300,
    },
    {
        "parameter": "stringer_spacing",
        "name": "次楞间距 l1（主楞方向）",
        "canonical_unit": "mm",
        "aliases": ["次楞计算跨度", "次龙骨计算跨度", "小楞跨度", "次楞间距"],
        "preferred_sections": ["模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["次楞", "次龙骨", "小楞"],
        "plausible_min": 100,
        "plausible_max": 1500,
    },
    {
        "parameter": "main_beam_section_width",
        "name": "主楞截面宽度 b",
        "canonical_unit": "mm",
        "aliases": ["主楞截面宽度", "主龙骨截面宽度", "大楞宽度", "双钢管宽度"],
        "preferred_sections": ["模板计算", "计算书", "材料"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["主楞", "主龙骨", "大楞"],
        "plausible_min": 30,
        "plausible_max": 300,
    },
    {
        "parameter": "main_beam_section_height",
        "name": "主楞截面高度 h",
        "canonical_unit": "mm",
        "aliases": ["主楞截面高度", "主龙骨截面高度", "大楞高度", "双钢管高度"],
        "preferred_sections": ["模板计算", "计算书", "材料"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["主楞", "主龙骨", "大楞"],
        "plausible_min": 30,
        "plausible_max": 300,
    },
    {
        "parameter": "main_beam_spacing",
        "name": "主楞间距 l2（立杆纵距方向）",
        "canonical_unit": "mm",
        "aliases": ["主楞间距", "主龙骨间距", "大楞间距", "主楞计算跨度"],
        "preferred_sections": ["模板计算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["主楞", "主龙骨", "大楞"],
        "plausible_min": 200,
        "plausible_max": 2000,
    },
    {
        "parameter": "vertical_axial_force",
        "name": "立杆轴力 N",
        "canonical_unit": "kN",
        "aliases": ["立杆轴力", "立杆轴力设计值", "立杆荷载设计值", "单肢立杆荷载", "单肢立杆荷载设计值", "Nd", "立杆受力"],
        "preferred_sections": ["支撑架计算", "立杆稳定性验算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["立杆轴力", "立杆荷载", "单肢立杆"],
        "plausible_min": 0.5,
        "plausible_max": 200.0,
    },
    {
        "parameter": "base_plate_area",
        "name": "垫板/底座面积 A",
        "canonical_unit": "mm2",
        "aliases": ["垫板面积", "底座面积", "立杆底座面积", "基础面积", "底板面积"],
        "preferred_sections": ["支撑架计算", "地基承载力验算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["垫板", "底座", "底板", "基础面积"],
        "plausible_min": 100,    # 0.01m² = 10000mm²
        "plausible_max": 1000000,  # 1m² = 1_000_000mm²
    },
    {
        "parameter": "foundation_bearing_capacity",
        "name": "地基承载力特征值 fa",
        "canonical_unit": "kPa",
        "aliases": ["地基承载力特征值", "地基承载力设计值", "承载力特征值", "fak", "fa"],
        "preferred_sections": ["支撑架计算", "地基承载力验算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"\bfa\b", r"\bfak\b", r"地基承载力特征值", r"地基承载力设计值", r"承载力特征值"],
        "include_terms": ["承载力", "fa", "fak"],
        "plausible_min": 30,
        "plausible_max": 800,
    },
    {
        "parameter": "structure_importance_factor",
        "name": "结构重要性系数 γ0",
        "canonical_unit": None,
        "aliases": ["γ0", "结构重要性系数", "重要性系数", "gamma0"],
        "preferred_sections": ["抗倾覆验算", "荷载组合", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "symbolic_numeric",
        "symbol_labels": [r"γ0", r"γ_0", r"结构重要性系数", r"重要性系数"],
        "include_terms": ["γ0", "重要性"],
        "plausible_min": 0.9,
        "plausible_max": 1.2,
    },
    {
        "parameter": "resisting_moment",
        "name": "抗倾覆力矩 MR / Mr",
        "canonical_unit": "kN·m",
        "aliases": ["抗倾覆力矩", "MR", "Mr", "抗倾覆力矩设计值"],
        "preferred_sections": ["抗倾覆验算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["抗倾覆", "MR", "Mr"],
        "plausible_min": 0.5,
        "plausible_max": 100000.0,
    },
    {
        "parameter": "overturning_moment",
        "name": "倾覆力矩 MT / Mo",
        "canonical_unit": "kN·m",
        "aliases": ["倾覆力矩", "MT", "Mo", "倾覆力矩设计值"],
        "preferred_sections": ["抗倾覆验算", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["倾覆", "MT", "Mo"],
        "plausible_min": 0.5,
        "plausible_max": 100000.0,
    },
    {
        "parameter": "wind_load",
        "name": "风荷载标准值 Wk",
        "canonical_unit": "kN/m2",
        "aliases": ["风荷载标准值", "风荷载", "Wk", "Wo", "基本风压", "风压"],
        "preferred_sections": ["抗倾覆验算", "荷载设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table", "body"],
        "extraction_mode": "numeric",
        "include_terms": ["风荷载", "风压", "Wk", "Wo"],
        "plausible_min": 0.05,
        "plausible_max": 2.0,
    },
    {
        "parameter": "wind_pressure_height",
        "name": "风压高度变化系数 μz 对应高度",
        "canonical_unit": "m",
        "aliases": ["风压高度", "风压高度变化系数对应高度", "μz对应高度", "架体顶面高度"],
        "preferred_sections": ["抗倾覆验算", "荷载设计", "计算书"],
        "expected_block_types": ["paragraph", "table"],
        "patterns": [],
        "source_priority": ["calculation", "parameter_table"],
        "extraction_mode": "numeric",
        "include_terms": ["风压高度", "μz", "架体顶面"],
        "plausible_min": 1.0,
        "plausible_max": 100.0,
    },
]


def get_parameter_definitions() -> list[dict[str, Any]]:
    return [dict(item) for item in PARAMETER_DEFINITIONS]
